# Esse makefile está inutilizado por enquanto...
Main: Main.hs MovimentosLogicos.hs TermSize.hs Api.hs Base.hs
	ghc Main.hs

all: run

run: Main
	./Main

clean:
	-rm -rf *.hi *.o Main Base Api MovimentosLogicos
